server.port: 8080

spring:  
  h2:
    console:
      enabled: true
  file:
    path: logs      
  datasource:
    url: jdbc:log4jdbc:h2:mem:testdb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password:    
    initialization-mode: always
    data: classpath:sql/schema.sql, classpath:sql/data.sql    